// <auto-generated />
namespace DocumentManagementApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DocumentDB_V3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DocumentDB_V3));
        
        string IMigrationMetadata.Id
        {
            get { return "202103111249290_DocumentDB_V3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
